format_version: 10
pipelines:
  backend:
    group: App-deployment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-0581b96:
        git: https://github.com/Khaleel221/Expense-Ansible.git
        shallow_clone: true
        auto_update: true
        branch: main
stages:
  - DEV:
      fetch_materials: true
      jobs:
        ansible:
          timeout: 0
          tasks:
            - exec:
                command: /home/ec2-user/.local/bin/ansible-playbook
                arguments:
                  - -i
                  - backend-dev.khaleel221.shop,
                  - -e
                  - ansible_user=ec2-user
                  - -e
                  - ansible_password=DevOps321
                  - -e
                  - env=dev
                  - -e
                  - role_name=backend
                  - expense.yml
