format_version: 10
pipelines:
  backend:
    group: App-deployment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-0581b96:
        git: https://github.com/Khaleel221/Expense-Ansible.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - DEV: # name of stage
          fetch_materials: true
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - --version
                    command: ansible
