format_version: 10
pipelines:
  Templates:
    group: ansible-app-deplyment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-0581b96:
        git: https://github.com/Khaleel221/Expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:HouDbUqrHm6wO/DVEkB59Q==:Xhmhx3vW4sbcZgqjc293qw=="
    environment_variables:
      pipeline: “true”
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          environment_variables:
            env: dev
          jobs:
            Ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                    command: bash

      - QA:
          fetch_materials: true
          environment_variables:
            env: qa
          approval:
            type: manual
          jobs:
            Ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                    command: bash
                    run_if: passed

      - STAGE:
          fetch_materials: true
          environment_variables:
            env: stage
          approval:
            type: manual
          jobs:
            Ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                    command: bash
                    run_if: passed

      - PROD:
          fetch_materials: true
          environment_variables:
            env: prod
          approval:
            type: manual
          jobs:
            Ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                    command: bash
                    run_if: passed